apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress
  labels:
    app: taskmanager
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: taskmanager-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: taskmanager-frontend
                port:
                  number: {{ .Values.frontend.service.port }}