apiVersion: v2
name: taskmanager
description: 3-tier Task Manager - React, Node.js, PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - react
  - nodejs
  - postgresql
maintainers:
  - name: your-name
    email: your@email.com