# ── Global ──────────────────────────────────────────────────
global:
  imageRegistry: ""        # e.g. your ECR URL in Phase 3

# ── Frontend ────────────────────────────────────────────────
frontend:
  image:
    repository: 751530150420.dkr.ecr.us-east-1.amazonaws.com/k8s-frontend
    tag: "f4dcea3d122c42e81fece995de4d990d6234f3c2"
    pullPolicy: Always
  replicaCount: 2
  port: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

backend:
  image:
    repository: 751530150420.dkr.ecr.us-east-1.amazonaws.com/k8s-backend
    tag: "f4dcea3d122c42e81fece995de4d990d6234f3c2"
    pullPolicy: Always
  replicaCount: 2
  port: 5000
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  hpa:
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

database:
  image:
    repository: 751530150420.dkr.ecr.us-east-1.amazonaws.com/k8s-db
    tag: "f4dcea3d122c42e81fece995de4d990d6234f3c2"
    pullPolicy: Always
  port: 5432
  name: taskdb
  user: postgres
  storage: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  

secrets:
  dbPassword: "devpassword123"